name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - hydra-core=1.3.2
  - matplotlib=3.8.2
  - pandas=2.2.3
  - pip=23.3.1
  - scikit-learn=1.3.2
  - jupyterlab=4.1.3
  - pip:
      - mlflow==2.14.3
      - wandb==0.17.5
      - ydata-profiling==4.12.1
