name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas=2.2.3
  - pytest=8.3.4
  - scipy=1.15.0
  - pip=23.3.1
  - pip:
      - mlflow==2.14.3
      - wandb==0.17.5
