name: test_regression_model
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=23.3.1
  - requests=2.24.0
  - scikit-learn=1.3.2
  - pandas=2.2.3
  - pip:
      - mlflow==2.14.3
      - wandb==0.17.5
      - git+https://github.com/erick-alv/build-ml-pipeline-for-short-term-rental-prices.git#egg=wandb-utils&subdirectory=components
