name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=23.3.1
  - requests=2.24.0
  - pip:
      - mlflow==2.14.3
      - wandb==0.17.5
      #- git+https://github.com/udacity/nd0821-c2-build-model-workflow-starter.git#egg=wandb-utils&subdirectory=components
